version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "lab-sample-api"
    IMAGE_TAG: $CODEBUILD_RESOLVED_SOURCE_VERSION

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 561099135374.dkr.ecr.us-east-1.amazonaws.com/lab-sample-api:$IMAGE_TAG

  post_build:
    commands:
      - docker push 123456789012.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - "**/*"
