version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "lab-sample-api"

phases:
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest 561099135374.dkr.ecr.us-east-1.amazonaws.com/lab-sample-api:latest

  post_build:
    commands:
      - docker push 561099135374.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:latest

artifacts:
  files:
    - "**/*"
